#+TITLE: Case Study - Titanic Survival


* Case Study - Titanic Survival
** Feature Extraction
Here we will talk about an important piece of machine learning: the extraction
of quantitative features from data. By the end of this section you will

 - Know how features are extracted from real-world data.
 - See an example of extracting numerical features from textual data

 In addition, we will go over several basic tools within scikit-learn which can
 be used to accomplish the above tasks.

** What Are Features?
*** Numerical Features
Recall that data in scikit-learn is expected to be in two-dimensional arrays, of
size n_samples ×× n_features.

Previously, we looked at the iris dataset, which has 150 samples and 4 features


#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.data.shape)
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[48]:
:END:

These features are:

 - sepal length in cm
 - sepal width in cm
 - petal length in cm
 - petal width in cm

Numerical features such as these are pretty straightforward: each sample
contains a list of floating-point numbers corresponding to the features

*** Categorical Features
What if you have categorical features? For example, imagine there is data on the
color of each iris:

color in [red, blue, purple]

You might be tempted to assign numbers to these features, i.e. red=1, blue=2,
purple=3 but in general this is a bad idea. Estimators tend to operate under the
assumption that numerical features lie on some continuous scale, so, for
example, 1 and 2 are more alike than 1 and 3, and this is often not the case for
categorical features.

In fact, the example above is a subcategory of "categorical" features, namely,
"nominal" features. Nominal features don't imply an order, whereas "ordinal"
features are categorical features that do imply an order. An example of ordinal
features would be T-shirt sizes, e.g., XL > L > M > S.

One work-around for parsing nominal features into a format that prevents the
classification algorithm from asserting an order is the so-called one-hot
encoding representation. Here, we give each category its own dimension.

The enriched iris feature set would hence be in this case:

 - sepal length in cm
 - sepal width in cm
 - petal length in cm
 - petal width in cm
 - color=purple (1.0 or 0.0)
 - color=blue (1.0 or 0.0)
 - color=red (1.0 or 0.0)

Note that using many of these categorical features may result in data which is
better represented as a sparse matrix, as we'll see with the text classification
example below.

*** Using the DictVectorizer to encode categorical features
When the source data is encoded has a list of dicts where the values are either
strings names for categories or numerical values, you can use the DictVectorizer
class to compute the boolean expansion of the categorical features while leaving
the numerical features unimpacted:


#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
measurements = [
    {'city': 'Dubai', 'temperature': 33.},
    {'city': 'London', 'temperature': 12.},
    {'city': 'San Francisco', 'temperature': 18.},
]
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[49]:
:END:

#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
vec

vec.fit_transform(measurements).toarray()

vec.get_feature_names()
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[50]:
: ['city=Dubai', 'city=London', 'city=San Francisco', 'temperature']
:END:

** Derived Features
Another common feature type are derived features, where some pre-processing step
is applied to the data to generate features that are somehow more informative.
Derived features may be based in feature extraction and dimensionality reduction
(such as PCA or manifold learning), may be linear or nonlinear combinations of
features (such as in polynomial regression), or may be some more sophisticated
transform of the features.

** Combining Numerical and Categorical Features
As an example of how to work with both categorical and numerical data, we will
perform survival predicition for the passengers of the HMS Titanic.

We will use a version of the Titanic (titanic3.xls) from here. We converted the
.xls to .csv for easier manipulation but left the data is otherwise unchanged.

We need to read in all the lines from the (titanic3.csv) file, set aside the
keys from the first line, and find our labels (who survived or died) and data
(attributes of that person). Let's look at the keys and some corresponding
example lines.


#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
import os
import pandas as pd

titanic = pd.read_csv(os.path.join('datasets', 'titanic3.csv'))
print(titanic.columns)
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[51]:
:END:

Here is a broad description of the keys and what they mean:

| pclass    | Passenger Class                                  |
|           | (1 = 1st; 2 = 2nd; 3 = 3rd)                      |
| survival  | Survival                                         |
|           | (0 = No; 1 = Yes)                                |
| name      | Name                                             |
| sex       | Sex                                              |
| age       | Age                                              |
| sibsp     | Number of Siblings/Spouses Aboard                |
| parch     | Number of Parents/Children Aboard                |
| ticket    | Ticket Number                                    |
| fare      | Passenger Fare                                   |
| cabin     | Cabin                                            |
| embarked  | Port of Embarkation                              |
|           | (C = Cherbourg; Q = Queenstown; S = Southampton) |
| boat      | Lifeboat                                         |
| body      | Body Identification Number                       |
| home.dest | Home/Destination                                 |

In general, it looks like name, sex, cabin, embarked, boat, body, and homedest
may be candidates for categorical features, while the rest appear to be
numerical features. We can also look at the first couple of rows in the dataset
to get a better understanding:


#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
titanic.head()
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[52]:
#+BEGIN_EXAMPLE
  pclass  survived                                             name     sex  \
  0       1         1                    Allen, Miss. Elisabeth Walton  female
  1       1         1                   Allison, Master. Hudson Trevor    male
  2       1         0                     Allison, Miss. Helen Loraine  female
  3       1         0             Allison, Mr. Hudson Joshua Creighton    male
  4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female

  age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
  0  29.0000      0      0   24160  211.3375       B5        S    2    NaN
  1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN
  2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN
  3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0
  4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN

  home.dest
  0                     St Louis, MO
  1  Montreal, PQ / Chesterville, ON
  2  Montreal, PQ / Chesterville, ON
  3  Montreal, PQ / Chesterville, ON
  4  Montreal, PQ / Chesterville, ON
#+END_EXAMPLE
:END:

We clearly want to discard the "boat" and "body" columns for any classification
into survived vs not survived as they already contain this information. The name
is unique to each person (probably) and also non-informative. For a first try,
we will use "pclass", "sibsp", "parch", "fare" and "embarked" as our features:

#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
labels = titanic.survived.values
features = titanic[['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked']]
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[53]:
:END:

#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
features.head()

#+END_SRC

#+RESULTS:
:RESULTS:
# Out[54]:
#+BEGIN_EXAMPLE
  pclass     sex      age  sibsp  parch      fare embarked
  0       1  female  29.0000      0      0  211.3375        S
  1       1    male   0.9167      1      2  151.5500        S
  2       1  female   2.0000      1      2  151.5500        S
  3       1    male  30.0000      1      2  151.5500        S
  4       1  female  25.0000      1      2  151.5500        S
#+END_EXAMPLE
:END:

The data now contains only useful features, but they are not in a format that
the machine learning algorithms can understand. We need to transform the strings
"male" and "female" into binary variables that indicate the gender, and
similarly for "embarked". We can do that using the pandas get_dummies function:


#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
pd.get_dummies(features).head()
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[55]:
#+BEGIN_EXAMPLE
  pclass      age  sibsp  parch      fare  sex_female  sex_male  embarked_C  \
  0       1  29.0000      0      0  211.3375           1         0           0
  1       1   0.9167      1      2  151.5500           0         1           0
  2       1   2.0000      1      2  151.5500           1         0           0
  3       1  30.0000      1      2  151.5500           0         1           0
  4       1  25.0000      1      2  151.5500           1         0           0

  embarked_Q  embarked_S
  0           0           1
  1           0           1
  2           0           1
  3           0           1
  4           0           1
#+END_EXAMPLE
:END:

This transformation successfully encoded the string columns. However, one might
argue that the class is also a categorical variable. We can explicitly list the
columns to encode using the columns parameter, and include pclass:


#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
features_dummies = pd.get_dummies(features, columns=['pclass', 'sex', 'embarked'])
features_dummies.head(n=16)

#+END_SRC

#+RESULTS:
:RESULTS:
# Out[56]:
#+BEGIN_EXAMPLE
  age  sibsp  parch      fare  pclass_1  pclass_2  pclass_3  sex_female  \
  0   29.0000      0      0  211.3375         1         0         0           1
  1    0.9167      1      2  151.5500         1         0         0           0
  2    2.0000      1      2  151.5500         1         0         0           1
  3   30.0000      1      2  151.5500         1         0         0           0
  4   25.0000      1      2  151.5500         1         0         0           1
  5   48.0000      0      0   26.5500         1         0         0           0
  6   63.0000      1      0   77.9583         1         0         0           1
  7   39.0000      0      0    0.0000         1         0         0           0
  8   53.0000      2      0   51.4792         1         0         0           1
  9   71.0000      0      0   49.5042         1         0         0           0
  10  47.0000      1      0  227.5250         1         0         0           0
  11  18.0000      1      0  227.5250         1         0         0           1
  12  24.0000      0      0   69.3000         1         0         0           1
  13  26.0000      0      0   78.8500         1         0         0           1
  14  80.0000      0      0   30.0000         1         0         0           0
  15      NaN      0      0   25.9250         1         0         0           0

  sex_male  embarked_C  embarked_Q  embarked_S
  0          0           0           0           1
  1          1           0           0           1
  2          0           0           0           1
  3          1           0           0           1
  4          0           0           0           1
  5          1           0           0           1
  6          0           0           0           1
  7          1           0           0           1
  8          0           0           0           1
  9          1           1           0           0
  10         1           1           0           0
  11         0           1           0           0
  12         0           1           0           0
  13         0           0           0           1
  14         1           0           0           1
  15         1           0           0           1
#+END_EXAMPLE
:END:

#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
data = features_dummies.values

#+END_SRC

#+RESULTS:
:RESULTS:
# Out[57]:
:END:

#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
import numpy as np
np.isnan(data).any()

#+END_SRC

#+RESULTS:
:RESULTS:
# Out[58]:
: True
:END:

With all of the hard data loading work out of the way, evaluating a classifier
on this data becomes straightforward. Setting up the simplest possible model, we
want to see what the simplest score can be with DummyClassifier.


#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
  from sklearn.model_selection import train_test_split
  from sklearn.preprocessing import Imputer
  train_data, test_data, train_labels, test_labels = train_test_split(
      data, labels, random_state=0)
  imp = Imputer()
  imp.fit(train_data)
  train_data_finite = imp.transform(train_data)
  test_data_finite = imp.transform(test_data)
#+END_SRC

#+RESULTS:
:RESULTS:
# Out[60]:
:END:

#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
np.isnan(train_data_finite).any()

#+END_SRC

#+RESULTS:
:RESULTS:
# Out[61]:
: False
:END:

#+BEGIN_SRC ipython :session :exports both :async t :results raw drawer
  from sklearn.dummy import DummyClassifier

  clf = DummyClassifier('most_frequent')
  clf.fit(train_data_finite, train_labels)
  print("Prediction accuracy: %f"
        % clf.score(test_data_finite, test_labels))

#+END_SRC

#+RESULTS:
:RESULTS:
# Out[62]:
:END:

EXERCISE: Try executing the above classification, using LogisticRegression and
RandomForestClassifier instead of DummyClassifier Does selecting a different
subset of features help?

# %load solutions/10_titanic.py
